In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(PROJECT_ROOT / "src"))

RAW_DIR = PROJECT_ROOT / "data" / "raw_transcripts"
NORMALIZED_DIR = PROJECT_ROOT / "data" / "processed" / "normalized_transcripts"

NORMALIZED_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Raw transcripts:", RAW_DIR)
print("Normalized output:", NORMALIZED_DIR)

Project root: c:\Users\Nadine Samir\Marina\NLP-project
Raw transcripts: c:\Users\Nadine Samir\Marina\NLP-project\data\raw_transcripts
Normalized output: c:\Users\Nadine Samir\Marina\NLP-project\data\processed\normalized_transcripts

In [2]:
from nomralization import normalize_arabic_for_rag

transcript_files = list(RAW_DIR.glob("*.txt"))

print("Found transcripts:", len(transcript_files))
for file in transcript_files:
    print("-", file.name)

Found transcripts: 4
- الأخطبوط  الدحيح.txt
- الساموراي  الدحيح.txt
- تاج محل  الدحيح.txt
- فيزياء و فلسفة الحركة  الدحيح.txt

Transcripts normalization

In [3]:
for file_path in transcript_files:
    raw_text = file_path.read_text(encoding="utf-8")
    normalized_text = normalize_arabic_for_rag(raw_text)

    output_path = NORMALIZED_DIR / file_path.name
    output_path.write_text(normalized_text, encoding="utf-8")

    print(f"Saved normalized transcript: {output_path.name}")

Saved normalized transcript: الأخطبوط  الدحيح.txt
Saved normalized transcript: الساموراي  الدحيح.txt
Saved normalized transcript: تاج محل  الدحيح.txt
Saved normalized transcript: فيزياء و فلسفة الحركة  الدحيح.txt

Sample Nomralized

In [4]:
sample_file = transcript_files[0]
raw_sample = sample_file.read_text(encoding="utf-8")[:1000]
normalized_sample = normalize_arabic_for_rag(raw_sample)

print("RAW SAMPLE:\n")
print(raw_sample)

print("\n" + "="*80 + "\n")

print("NORMALIZED SAMPLE:\n")
print(normalized_sample)

RAW SAMPLE:

6.45: يا ربي!
7.756: أنا زهقت!
8.396: ما تثبت يا ابني بقى،
9.564: اثبت، تعبتني!
10.846: سيب الجهاز يقرا!
11.712: بصراحة، أنا مش عاجبني موضوع التجربة دي،
13.843: أنا قُلت: الموضوع فيه Seafood،
15.775: فقُلت: هيبقى فيه أكلة سمك حلوة.
17.875: يا حبيبي، التجربة دي لو نجحت،
19.521: هتبقى أول إنسان
نُص بني آدم، ونُص أخطبوط في التاريخ.
23.864: وإيه المبهر لمّا أبقى نُص أخطبوط؟!
25.41: دا عادي، يتّاكل جنب السُبّيط
وشوية رُز صيادية،
28.616: عادي، مش حاجة فظيعة يعني.
30.037: صيادية إيه؟! انت بتقول إيه؟!
32.233: انت هيبقى عندك قدرات الأخطبوط،
هيبقى عندك قدرات خارقة،
35.285: هتقدر مثلًا تعمل Multi-Tasking.
37.296: إيه يعني Multi-Tasking؟!
38.715: أي موظف، ولّا أي طفل في مدرسة،
41.481: بيعمل موضوع الـMulti-Tasking دا.
43.111: طب إيه رأيك، أنا الصبح محاسب،
44.737: الضهر Designer،
45.928: بالليل "أوبر"،
46.882: وبأعمل "تراكات" راب.
48.037: يا سيدي، بلاش،
50.185: كفاية إن الأخطبوط عنده 3 قلوب،
52.781: متخيل؟!
53.733: في دي، عندك حق، أنا عندي قلب واحد،
56.002: بس القلب الواحد دا، بعون الله،
58.184: بيح

================================================================================

NORMALIZED SAMPLE:

يا ربي! انا زهقت! ما تثبت يا ابني بقي، اثبت، تعبتني! سيب الجهاز يقرا! بصراحة، انا مش عاجبني موضوع التجربة دي، انا قلت: الموضوع فيه Seafood، فقلت: هيبقي فيه اكلة سمك حلوة. يا حبيبي، التجربة دي لو نجحت، هتبقي اول انسان نص بني ادم، ونص اخطبوط في التاريخ. وايه المبهر لما ابقي نص اخطبوط؟! دا عادي، يتاكل جنب السبيط وشوية رز صيادية، عادي، مش حاجة فظيعة يعني. صيادية ايه؟! انت بتقول ايه؟! انت هيبقي عندك قدرات الاخطبوط، هيبقي عندك قدرات خارقة، هتقدر مثلا تعمل Multi-Tasking. ايه يعني Multi-Tasking؟! اي موظف، ولا اي طفل في مدرسة، بيعمل موضوع الMulti-Tasking دا. طب ايه رايك، انا الصبح محاسب، الضهر Designer، بالليل "اوبر"، وباعمل "تراكات" راب. يا سيدي، بلاش، كفاية ان الاخطبوط عنده 3 قلوب، متخيل؟! في دي، عندك حق، انا عندي قلب واحد، بس القلب الواحد دا، بعون الله، بيح

Chunking

In [5]:
from chunking import build_chunks_from_folder

chunks = build_chunks_from_folder(
    normalized_dir=NORMALIZED_DIR,
    chunk_size=350,
    overlap=70
)

print("Total chunks:", len(chunks))
print("Example chunk keys:", chunks[0].keys())
print("Example episode:", chunks[0]["episode"])
print("Example chunk ID:", chunks[0]["chunk_id"])

Total chunks: 75
Example chunk keys: dict_keys(['chunk_id', 'episode', 'source_file', 'text'])
Example episode: الأخطبوط  الدحيح
Example chunk ID: الأخطبوط  الدحيح_chunk_0

Chunking Sample

In [6]:
print(chunks[0]["text"][:1500])

يا ربي! انا زهقت! ما تثبت يا ابني بقي، اثبت، تعبتني! سيب الجهاز يقرا! بصراحة، انا مش عاجبني موضوع التجربة دي، انا قلت: الموضوع فيه Seafood، فقلت: هيبقي فيه اكلة سمك حلوة. يا حبيبي، التجربة دي لو نجحت، هتبقي اول انسان نص بني ادم، ونص اخطبوط في التاريخ. وايه المبهر لما ابقي نص اخطبوط؟! دا عادي، يتاكل جنب السبيط وشوية رز صيادية، عادي، مش حاجة فظيعة يعني. صيادية ايه؟! انت بتقول ايه؟! انت هيبقي عندك قدرات الاخطبوط، هيبقي عندك قدرات خارقة، هتقدر مثلا تعمل Multi-Tasking. ايه يعني Multi-Tasking؟! اي موظف، ولا اي طفل في مدرسة، بيعمل موضوع الMulti-Tasking دا. طب ايه رايك، انا الصبح محاسب، الضهر Designer، بالليل "اوبر"، وباعمل "تراكات" راب. يا سيدي، بلاش، كفاية ان الاخطبوط عنده 3 قلوب، متخيل؟! في دي، عندك حق، انا عندي قلب واحد، بس القلب الواحد دا، بعون الله، بيحب "سهي" و"نهي" و"ليلي" و"سلمي" و"دعاء" و"شيماء"، و2 صحابي كمان. دا غير مراتي طبعا، والحلاق. ايه كمان في الاخطبوط؟ انت متخيل... ممكن تعمل ايه لما يبقي عندك 8 رجول؟ 8 رجول؟! انت عارف الكوتشي الفردتين يعمله كام دلوقتي؟ مصاريف علي الفاضي! هاقعد اشتري لكل رجل جزمة؟ انت عارف ان الاخطبوط ذكي جدا؟ وهو الذكاء بيجيب ايه غير الهم والغم ووجع القلب؟! يا عم، العبيط عايش في احلي دنيا، خليني انا في نعيم الجهل، واتبسط انت بجحيم الوعي. طب الاخطبوط، علي فكرة، بيعرف يصنع حبر. قلمين فرنساوي هنا من المكتبة، اظروطلك الدنيا حبر. وبعدين بقعته ما بتخرجش بالمسحوق، يعني، وساخة علي الفاضي! ياه! انت محبط جدا، علي فكرة! قوم يا عم، خلاص، بلاش تجارب ولا نيلة! استهدي انت بالله يا عم، وقوم اسلقلنا الاخطبوط اللي جوا، شوية عيش، شوية سلاطات، شوية طحينات، انا متاكد، ك

Save chunks as JSON

In [7]:
import json

CHUNKS_PATH = PROJECT_ROOT / "data" / "processed" / "chunks.json"

with open(CHUNKS_PATH, "w", encoding="utf-8") as f:
    json.dump(chunks, f, ensure_ascii=False, indent=2)

print("Saved chunks to:", CHUNKS_PATH)

Saved chunks to: c:\Users\Nadine Samir\Marina\NLP-project\data\processed\chunks.json

Embedding Step

In [8]:
from embeddings import EmbeddingModel

embedding_model = EmbeddingModel()

chunk_texts = [chunk["text"] for chunk in chunks]

chunk_embeddings = embedding_model.embed_texts(chunk_texts)

print("Number of chunks:", len(chunk_texts))
print("Embedding shape:", chunk_embeddings.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/3 [00:00<?, ?it/s]

Number of chunks: 75
Embedding shape: (75, 384)

Test one query embedding

In [9]:
query = "الأخطبوط ذكي ازاي؟"

query_embedding = embedding_model.embed_query(query)

print("Query embedding shape:", query_embedding.shape)

Query embedding shape: (384,)

Vector DB

In [10]:
from vector_store import ChromaVectorStore

VECTOR_DB_DIR = PROJECT_ROOT / "data" / "vector_db"

vector_store = ChromaVectorStore(
    persist_dir=VECTOR_DB_DIR,
    collection_name="arabic_transcripts_ms3"
)

print("Current vector DB count:", vector_store.count())

Current vector DB count: 75

Add chunks to vector DB (Store Embeddings)

In [11]:
if vector_store.count() == 0:
    vector_store.add_chunks(chunks, chunk_embeddings)
    print("Chunks added to vector DB.")
else:
    print("Vector DB already contains chunks. Skipping add.")

print("Final vector DB count:", vector_store.count())

Vector DB already contains chunks. Skipping add.
Final vector DB count: 75

Test semantic search

In [12]:
query = "الأخطبوط ذكي ازاي؟"

query_embedding = embedding_model.embed_query(query)

results = vector_store.search(
    query_embedding=query_embedding,
    top_k=3
)

for i in range(3):
    print("=" * 80)
    print("Result:", i + 1)
    print("Episode:", results["metadatas"][0][i]["episode"])
    print("Source:", results["metadatas"][0][i]["source_file"])
    print("Distance:", results["distances"][0][i])
    print(results["documents"][0][i][:1000])

================================================================================
Result: 1
Episode: الأخطبوط  الدحيح
Source: الأخطبوط  الدحيح.txt
Distance: 0.6171594262123108
الاخطبوط اكبر، كل ما كان عنده خبرة اكبر وفضول اقل، فتلاقي ان مع السن، الاخطبوط ما بقاش مهتم ان هو يحل اللغز، ولكن العكس مع الصغيرين، اللي بيبقوا متحمسين ان هما يحاولوا يحلوا اللغز، اختلاف الشخصيات بين الاخطبوطات دا بيرجع الي ان المخ كبير، فيه براح، ما يسبب الCognitive Flexibility. الاخطبوطات في الاحواض المائية مشهورة جدا انها احيانا بتخرج من الحوض تروح تجيب اكل، وترجع تاني، بس دا نقدر نقول ان هو عادي، بنعتبره بيصطاد، ولكن في جامعة "اوتاجو" في "نيوزيلاندا"، الاخطبوطات كانت بتكره النور الساطع، ليه؟ لانها، زي ما احنا عارفين، متعودة تعيش في قاع البحر، فاتعلمت، يا عزيزي، انها تطفي النور. فاكر افرازات الميه اللي حكيتلك عنها؟ احيانا، كانت الاخطبوطات بتستخدم هذه النفاثات في انها تحدف ميه، فتطفي اللمبة، ومش بس كدا، كانت بتحدف ميه علي اي حد مش عاجبها في المعمل. مرة، يا عزيزي، كان فيه اخطبوط عنده موقف عدائي تجاه موظفة، كانت كل مرة تعدي من قدام الحوض، يقوم راشش عليها! احد الباحثين كمان بياكد نفس السلوك، كان عنده حبار، اللي هو ابن عم الاخطبوط، كان بيرش ميه علي الزوار الجداد بس. وفي 2010، التجارب هت
================================================================================
Result: 2
Episode: الأخطبوط  الدحيح
Source: الأخطبوط  الدحيح.txt
Distance: 0.6533324122428894
يا عزيزي، اخطبوط اقل من جرام! اهو الحيوان قليل الحيلة دا، بقي من انجح افراد عيلته، جرام! لو جيت تاملت، هتجد ان المفارقة يمكن تكون ان الاخطبوط نجح بسبب قلة حيلته. الاخطبوط كائن لين، عشان كدا، سجله الاحفوري، لما تيجي تبص بقي في الحفريات، ما تلاقيهوش اوي، التحفر بيتطلب ان الكائن يتحفظ قبل ما الانسجة تتحلل، فالاجزاء الصلبة، زي الصدف او العضم مثلا، بيبقي عندها فرصة احسن انها تتحول الي حفريات، فالعلماء ييجوا يدرسوها، ويعرفوا اكتر عن هذا الكائن، وتطوره عبر التاريخ. لكن الحيوانات، اللي ما عندهاش اجزاء صلبة كدا، بنلاقيها قليلة اوي في السجل الاحفوري. بس هل دا معناه ان العلماء ما لقوش تاريخ للاخطبوط؟ لا، بالعكس، لقوا حفريات لاسلاف الاخطبوط زي المجموعة دي... معلش، تلاقيني، يا عزيزي، في الاحفوري مش اد كدا! المجموعة دي، لقوا فيها حاجة غريبة جدا، لقوا فيها بقايا صدفة، دا، بشكل او باخر، بيدل ان الاخطبوط زمان كان عنده صدفة، بالظبط زي معظم الرخويات، ولكنه مع الوقت فقدها. في 2015، هيتم نشر دراسة ضخمة في مجلة Nature، اول خريطة جينية كاملة للاخطبوط، وبربط بقي الادلة بتاعة الحفريات والتشريح والتحليل الجيني،
================================================================================
Result: 3
Episode: الأخطبوط  الدحيح
Source: الأخطبوط  الدحيح.txt
Distance: 0.7141562104225159
الاخطبوط هنا ما اخترعش الية جديدة، هو اعاد توظيف الية موجودة، بس في حتة تانية، ودي بالظبط عبقرية الاخطبوط، هو مش كائن فضائي، ما عندهوش اليات خارقة، ولكن ترتيبة جسمه استثنائية. بس خد بالك، التمويه دا ليس مجاني، في تجربة اتعملت علي الاخطبوط الياقوتي الشرقي، سلطوا ضوء ازرق، عشان ينشط خلايا الالوان، وقاموا عاملين مقارنة، والمقارنة هتعتمد علي استهلاك الاكسجين قبل وبعد التنشيط، هنشوف بيستهلك اكسجين اد ايه لما ينشط، عشان يقدروا يحسبوا الCalories، الطاقة اللي بيتم استخدامها في حاجة زي كدا. وجدوا، يا عزيزي، ان جهاز التمويه دا، اللي هو شوية خلايا صغيرة في الجلد، بتستهلك اد باقي الجسم كله، انت بتتكلم هنا علي المخ والاعضاء والدراعات، كل دا، يا عزيزي، من غير ما احط في الحسبة الملمس بتاع الجلد، فانت مش بس نظري، انت كمان Texture. فغالبا، الاخطبوط بيستهلك طاقة، عشان يقدر يموه اكتر من اي حيوان. عشان كدا، احسن حاجة يعملها هي انه يهرب، ودا برضه، عنده Technique فيه. الاخطبوط عنده عضو اسمه كيس الحبر، دا موجود جنب الجهاز الهضمي والمثانة، فيه غدد بتعمل الحبر، وقت الخطر، الاخطبوط بيقوم قابض عضلاته، فيخرج الحب

Retriever of most similar chunks to query

In [13]:
from retriever import Retriever

retriever = Retriever(
    embedding_model=embedding_model,
    vector_store=vector_store,
    top_k=5
)

In [14]:
query = "الأخطبوط ذكي ازاي؟"

retrieved_chunks = retriever.retrieve(query)

for chunk in retrieved_chunks:
    print("=" * 80)
    print("Rank:", chunk["rank"])
    print("Episode:", chunk["episode"])
    print("Distance:", chunk["distance"])
    print(chunk["text"][:700])

================================================================================
Rank: 1
Episode: الأخطبوط  الدحيح
Distance: 0.6171594262123108
الاخطبوط اكبر، كل ما كان عنده خبرة اكبر وفضول اقل، فتلاقي ان مع السن، الاخطبوط ما بقاش مهتم ان هو يحل اللغز، ولكن العكس مع الصغيرين، اللي بيبقوا متحمسين ان هما يحاولوا يحلوا اللغز، اختلاف الشخصيات بين الاخطبوطات دا بيرجع الي ان المخ كبير، فيه براح، ما يسبب الCognitive Flexibility. الاخطبوطات في الاحواض المائية مشهورة جدا انها احيانا بتخرج من الحوض تروح تجيب اكل، وترجع تاني، بس دا نقدر نقول ان هو عادي، بنعتبره بيصطاد، ولكن في جامعة "اوتاجو" في "نيوزيلاندا"، الاخطبوطات كانت بتكره النور الساطع، ليه؟ لانها، زي ما احنا عارفين، متعودة تعيش في قاع البحر، فاتعلمت، يا عزيزي، انها تطفي النور. فاكر افرازات الميه اللي حكيتلك عنها؟ احيانا، كانت الاخطبوطات بتستخدم هذه النفاثات في انها تحدف ميه، فتطفي اللم
================================================================================
Rank: 2
Episode: الأخطبوط  الدحيح
Distance: 0.6533324122428894
يا عزيزي، اخطبوط اقل من جرام! اهو الحيوان قليل الحيلة دا، بقي من انجح افراد عيلته، جرام! لو جيت تاملت، هتجد ان المفارقة يمكن تكون ان الاخطبوط نجح بسبب قلة حيلته. الاخطبوط كائن لين، عشان كدا، سجله الاحفوري، لما تيجي تبص بقي في الحفريات، ما تلاقيهوش اوي، التحفر بيتطلب ان الكائن يتحفظ قبل ما الانسجة تتحلل، فالاجزاء الصلبة، زي الصدف او العضم مثلا، بيبقي عندها فرصة احسن انها تتحول الي حفريات، فالعلماء ييجوا يدرسوها، ويعرفوا اكتر عن هذا الكائن، وتطوره عبر التاريخ. لكن الحيوانات، اللي ما عندهاش اجزاء صلبة كدا، بنلاقيها قليلة اوي في السجل الاحفوري. بس هل دا معناه ان العلماء ما لقوش تاريخ للاخطبوط؟ لا، بالعكس، لقوا حفريات لاسلاف الاخطبوط زي المجموعة دي... معلش، تلاقيني، يا عزيزي، في الاحفوري مش اد كد
================================================================================
Rank: 3
Episode: الأخطبوط  الدحيح
Distance: 0.7141562104225159
الاخطبوط هنا ما اخترعش الية جديدة، هو اعاد توظيف الية موجودة، بس في حتة تانية، ودي بالظبط عبقرية الاخطبوط، هو مش كائن فضائي، ما عندهوش اليات خارقة، ولكن ترتيبة جسمه استثنائية. بس خد بالك، التمويه دا ليس مجاني، في تجربة اتعملت علي الاخطبوط الياقوتي الشرقي، سلطوا ضوء ازرق، عشان ينشط خلايا الالوان، وقاموا عاملين مقارنة، والمقارنة هتعتمد علي استهلاك الاكسجين قبل وبعد التنشيط، هنشوف بيستهلك اكسجين اد ايه لما ينشط، عشان يقدروا يحسبوا الCalories، الطاقة اللي بيتم استخدامها في حاجة زي كدا. وجدوا، يا عزيزي، ان جهاز التمويه دا، اللي هو شوية خلايا صغيرة في الجلد، بتستهلك اد باقي الجسم كله، انت بتتكلم هنا علي المخ والاعضاء والدراعات، كل دا، يا عزيزي، من غير ما احط في الحسبة الملمس بتاع الجلد، فانت مش بس
================================================================================
Rank: 4
Episode: الأخطبوط  الدحيح
Distance: 0.7629029154777527
تانية، من غير ما يمرنوها، سابوهم يتعلموا من صاحبهم اللي اتعلم، وبالفعل، اتعلموا اسرع منه عن طريق المشاهدة، ان هما يشوفوه بيعمل ايه، وبداوا يعملوا زيه. هنا، يا عزيزي، دي حاجة Interesting جدا، لان هنا، الاخطبوط ربط حدث بنتيجة، واتعلم من بعيد، من غير ما يخوض التجربة بنفسه، ودا غريب جدا، لان الاخطبوط مش محتاج التعلم الاجتماعي، الاخطبوط بيعيش لوحده طول عمره، ما عدا في وقت التزاوج، احيانا، بنشوفه بيتعاون مع انواع تانية، زي مثلا، سمة التروات المفترس، احيانا، بيعملوا خطة هجمة، تخلي الفريسة مش عارفة الضربة جاية منين، السمكة بتدل الاخطبوط علي مكان الفريسة، يقوم رايح الاخطبوط يسيطر علي الفريسة بدراعاته، او يقوم مدخل دراعاته في الانفاق الضيقة، فيقوم طارد الفريسة. دا، يا عزيزي، تعاون، تبادل معلومات استخب
================================================================================
Rank: 5
Episode: الأخطبوط  الدحيح
Distance: 0.779876172542572
نتوءات صغيرة، عشان الملمس يبقي كان انت واقف علي صخور، كان انت بتشوف شعب مرجانية. بعض الانواع، زي الاخطبوط المقلد، لو قابل مفترس، زي الDamselfish، بيغير، يا عزيزي، شكله بالكامل، بيبقي عارف ايه؟ ممكن يعمل نفسه تعبان بحر، اللي هو المفترس الطبيعي للDamsel! وقدام كل مفترس، ممكن يتحول الي سمكة الاسد، او سمكة موسي، دا غير انه يقدر يتحول ل15 مخلوق تاني، فانت، يا عزيزي، مش معاك كائن، انت معاك Technology تتحولك ل15 كائن تاني! وسط الكائنات، يا عزيزي، كل ما كانت الوانك فاقعة، زاهية اوي، كل ما انت غالبا كنت سام، فالاخطبوط ممكن يلعب برضه بالحيلة دي، ممكن يبقي الوانه زاهية اكتر، بحيث ان المفترس لما يشوفهولك، يقولك: "اه! لا، لا، لا، اوعي تاكل من البتاع دا! دا ممكن يبقي سام." بيلعب في الوانه. الاخطبوط، مثلا،

Test English/mixed query

In [15]:
query = "What does the episode say about motion and physics?"

retrieved_chunks = retriever.retrieve(query)

for chunk in retrieved_chunks:
    print("=" * 80)
    print("Rank:", chunk["rank"])
    print("Episode:", chunk["episode"])
    print("Distance:", chunk["distance"])
    print(chunk["text"][:700])

================================================================================
Rank: 1
Episode: فيزياء و فلسفة الحركة  الدحيح
Distance: 1.1842942237854004
بعده "بولتزمان"، واكتشف ما يعرف بالEntropy، نظام عشوائي للحركة، والحركة دي بتولدلنا طاقة حراراية، يعني، لو ملينا كوباية ميه، هنلاقيها من بعيد ثابتة، ولكن في حقيقة الامر، جزيئات الميه اللي جوا الميه بتتحرك بشكل عشوائي في كل الاتجاهات، وعند درجة الغليان، الموضوع بيتحول الي حنة، فرح شعبي! جزيئات الميه بتتحرك بعشوائية وبجنون، وبطريقة وبنمط لا يمكن التنبؤ بيهم اطلاقا، احتمالات كتيرة جدا لكل جزيء في الميه. في كتابه، One Two Three... لحد الInfitinity، ان شاء الله، بيقول الفيزيائي "جورج جاموف" ان انت لو سخنت كوباية ميه، فاللي بيمنع الميه دي من انها تطير، هو تماسك الجزيئات دي بينها وبين بعضها، ولكن يظل هناك احتمال نظري ان نص الكوباية الفوقاني كل جزيئات بتتحرك لفوق، والنص التحتاني كل جزيئاته بتتحرك لت
================================================================================
Rank: 2
Episode: فيزياء و فلسفة الحركة  الدحيح
Distance: 1.203364610671997
اول، يا حبايبي، ما الفوتونات بتخبط فيه، بيتزق وبيغير سرعته، وبالتالي، بيغير مكانه." يعني الملاحظة نفسها، يا عزيزي، بتاثر علي حركة الالكترون. "طب، يا (ابو حميد)، دي مش مشكلة في الفيزيا، دي مشكلة في الادوات اللي بتقيس." الحقيقة، يا عزيزي، ان دي ليست مشكلة ادوات قياس، يعني، حتي لو استخدمت حاجة خيالية طبعا، ما بتعملش الEffect بتاع الفوتون، برضه، هتجد نفس المشكلة، الكون بيقولك: "Listen Your Obama دا قانون الكون! انت ليك عندي حاجة واحدة تخص الذرة، يا المكان، يا السرعة، اتصرف بقي، مش هتاخد الاتنين!" القانون نفسه بيقولك ان الطبيعة Fundamentally جواها، مش هتقولك حاجة بدقة! يعني، الالكترون فعليا ما عندهوش مكان وسرعة في نفس اللحظة، ومن هنا، يا عزيزي، ظهر "مبدا عدم اليقين"، وبقي فعل المراقبة نفسه جزء من
================================================================================
Rank: 3
Episode: فيزياء و فلسفة الحركة  الدحيح
Distance: 1.2118885517120361
اللي بيتحرك، ان ممكن يبقي فيه عدد لانهائي من الاكوان بتتحرك مع بعض، كل كون من الاكوان دي بيتحرك بقوانينه الفيزيائية الخاصة بيه. وفيه بقي، يا عزيزي، نظرية الاوتار الفائقة، ونسختها العجيبة نظرية "ام"، الM-Theory، ودي، يا عزيزي، بتقترح ان كل شيء من اول الذرة لحد المجرة مش كتل من المادة، ولكن اوتار دقيقة بتتهز، بتVibrate، اوتار بتتحرك وبتطلع نغمات، فبتولد انواع مختلفة من المادة والطاقة. ربما، يا عزيزي، قعدتك علي كوكب "الارض" ما خلتكش واعي بكل هذه الحركات، ولكن، مبدا الحركة، زي ما تقول كدا، ممكن يبقي عابر للعلوم، من الفيزيا للرياضيات لحياتك نفسها، حياتك اللي لازم تتحرك فيها كل لحظة، ما تقفش في مكانك، سواء عشان تجري ورا اتوبيس، او تجري ورا حلم. في النهاية، يا عزيزي، كونيا وانسانيا، زي ما شفنا في ه
================================================================================
Rank: 4
Episode: فيزياء و فلسفة الحركة  الدحيح
Distance: 1.332101583480835
كانت مسيطرة علي الفيزيا لاكتر من 1800 سنة، الا ان "جاليليو" بيقول: "يا جماعة، الكلام دا مش صح!" وفي تجربة عملية، بينفذها "جاليليو" بنفسه، علي حسب المصادر، بيقال ان هو طلع فوق برج "بيزا" المايل، علي مراي ومسمع من انصار "ارسطو"، وقام رامي جسمين، واحد تقيل والتاني خفيف، والمفاجاة، يا عزيزي، ان الجسمين بيوصلوا الارض في نفس اللحظة، مع ان هنا فيه واحد اتقل من التاني. يقال، يا عزيزي، ان انصار "ارسطو" لما شافوا هذا المنظر، قالوا: "احنا نكدب عينيا، نكدب اي حاجة، الا اننا نكدب عم (ارسطو)!" بصراحة، يا عزيزي، كتير من الاراء العلمية للفلاسفة القدماء نقدر نقول عليها اراء، من مقعدنا يعني دلوقتي، انها اراء ساذجة، ما ادخلهاش بيتي، برغم انها تبدو للوهلة الاولي اراء بديهية. يعني، منطقي جدا ان حد يبقي عنده انطب
================================================================================
Rank: 5
Episode: الأخطبوط  الدحيح
Distance: 1.3365483283996582
وكان اهم تحذير منه بيقوله ل"بيتر باركر"... الذكاء مسئولية، واهم حد يعلمهولنا هو الاخطبوط. بس كدا، يا عزيزي، اخيرا، وليس اخرا، ما تنساش تشوف الحلقات اللي فاتت، تشوف الحلقات الجاية، تنزل تبص علي المصادر، لو احنا علي ال"يوتيوب"، نشترك علي القناة.

Prompt Construction

In [16]:
from prompts import (
    build_context,
    build_minimal_prompt,
    build_strict_grounded_prompt,
    build_arabic_strict_prompt
)

query = "الأخطبوط ذكي ازاي؟"
retrieved_chunks = retriever.retrieve(query)

minimal_prompt = build_minimal_prompt(query, retrieved_chunks)
strict_prompt = build_strict_grounded_prompt(query, retrieved_chunks)
arabic_prompt = build_arabic_strict_prompt(query, retrieved_chunks)

print(strict_prompt[:3000])

You are an Arabic question-answering assistant.

You must answer using ONLY the provided context.

Rules:
1. Do not use outside knowledge.
2. If the answer is not clearly found in the context, say:
   "لا توجد معلومات كافية في النص للإجابة عن هذا السؤال."
3. Answer in the same language as the user's question.
4. If the question mixes Arabic and English, you may answer in Arabic with necessary English terms.
5. Keep the answer clear and concise.
6. Mention the source episode name at the end.

Retrieved context:
[Source: الأخطبوط  الدحيح | Rank: 1]
الاخطبوط اكبر، كل ما كان عنده خبرة اكبر وفضول اقل، فتلاقي ان مع السن، الاخطبوط ما بقاش مهتم ان هو يحل اللغز، ولكن العكس مع الصغيرين، اللي بيبقوا متحمسين ان هما يحاولوا يحلوا اللغز، اختلاف الشخصيات بين الاخطبوطات دا بيرجع الي ان المخ كبير، فيه براح، ما يسبب الCognitive Flexibility. الاخطبوطات في الاحواض المائية مشهورة جدا انها احيانا بتخرج من الحوض تروح تجيب اكل، وترجع تاني، بس دا نقدر نقول ان هو عادي، بنعتبره بيصطاد، ولكن في جامعة "اوتاجو" في "نيوزيلاندا"، الاخطبوطات كانت بتكره النور الساطع، ليه؟ لانها، زي ما احنا عارفين، متعودة تعيش في قاع البحر، فاتعلمت، يا عزيزي، انها تطفي النور. فاكر افرازات الميه اللي حكيتلك عنها؟ احيانا، كانت الاخطبوطات بتستخدم هذه النفاثات في انها تحدف ميه، فتطفي اللمبة، ومش بس كدا، كانت بتحدف ميه علي اي حد مش عاجبها في المعمل. مرة، يا عزيزي، كان فيه اخطبوط عنده موقف عدائي تجاه موظفة، كانت كل مرة تعدي من قدام الحوض، يقوم راشش عليها! احد الباحثين كمان بياكد نفس السلوك، كان عنده حبار، اللي هو ابن عم الاخطبوط، كان بيرش ميه علي الزوار الجداد بس. وفي 2010، التجارب هتثبت ان اخطبوط "المحيط الهادي" العملاق بيقدر يميز انسان عن التاني، حتي لو لابسين نفس اللبس. الاخطبوط مشهور بشقاوته، بيرمي الاكل اللي مش عاجبه في وشك، يهرب من الحوض، يستني لما تمشي، ويعمل حاجة. بس دي مجرد مش شقاوة، الاخطبوط اتعلم في الطبيعة ان هو بينجو ويهرب لما المفترس يبص الناحية التانية، ففضلت معاه مهارة لحد دلوقتي "هل الراجل دا مركز معايا دلوقتي؟ ولا لا؟" وعلي هذا الاساس، يهرب. الاخطبوط كمان في بعض التجارب اثبت انه بيتعلم بالمشاهدة، في تجربة سنة 92، حطوا للاخطبوط كورة حمرا وكورة بيضا، واتدرب انه لما هيلمس الكورة الحمرا، هياخد مكافاة، وبعد كدا، قاموا مدخلين اخطبوطات تانية، من غير ما يمرنوها، سابوهم يتعلموا من صاحبهم اللي اتعلم، وبالفعل، اتعلموا اسرع منه عن طريق المشاهدة، ان هما يشوفوه بيعمل ايه، وبداوا يعملوا زيه. هنا، يا عزيزي، دي حاجة Interesting جدا، لان هنا، الاخطبوط ربط حدث بنتيجة، واتعلم من بعيد، من غير ما يخوض التجربة بنفسه، ودا غريب جدا، لان الاخطبوط مش محتاج التعلم الاجتماعي، الاخطبوط بيعيش لوحده طول عمره، ما عدا في وقت التزاوج، احيانا، بنشوفه بيتعاون

---

[Source: الأخطبوط  الدحيح | Rank: 2]
يا عزيزي، اخطبوط اقل من جرام! اهو الحيوان قليل الحيلة دا، بقي من انجح افراد عيلته، جرام! لو جيت تاملت، هتجد ان المفارقة يمكن تكون ان الاخطبوط نجح بسبب قلة حيلته. الاخطبوط كائن لين، عشان كدا، سجله الاحفوري، لما تيجي تبص بقي في الحفريات، ما تلاقيهوش اوي، التحفر بيتطلب ان الكائن يتحفظ قبل ما الانسجة تتحلل، فالاجزاء الصلبة، زي الصدف او العضم مثلا، بيبقي عندها فرصة احسن انها تتحول الي حفريات، فالعلماء ييجوا يدرسوها، ويعرفوا اكتر

LLM APIs

In [17]:
# from llm_client import GeminiLLM

# llm = GeminiLLM()

# test_response = llm.generate("قل مرحبا بالعربية فقط.")
# print(test_response)

Groq

In [18]:
from llm_client_groq import GroqLLM

llm = GroqLLM()

response = llm.generate("say hi in english and arabic")

print(response)

**Hello in English:** Hello!

**Hello in Arabic:** مَرْحَبًا (Marhaba)

OpenAI

In [19]:
# from llm_client_openai import OpenAILLM

# llm_openai = OpenAILLM(model_name="gpt-3.5-turbo")

# response = llm.generate("say hi in english and arabic")
# print(response)

HuggingFace

In [20]:
from llm_client_hf import HuggingFaceLLM

hf_llm = HuggingFaceLLM(
    model_name="Qwen/Qwen2.5-7B-Instruct"
)

print(hf_llm.generate("قل مرحبا فقط بالعربية."))

مرحبا

Connect Retriever + Prompt + LLM

In [21]:
# Groq
from prompts import build_strict_grounded_prompt

query = "الأخطبوط ذكي ازاي؟"

retrieved_chunks = retriever.retrieve(query)

prompt = build_strict_grounded_prompt(
    question=query,
    retrieved_chunks=retrieved_chunks
)

answer = llm.generate(prompt)

print(answer)

الأخطبوط ذكي لانة بتستخدم الية موجودة في جسمها، زي مثلا، بروتينات حساسة للضوء في جلدها، وبتستخدمها في التمويه، وبتستخدم خلايا الالوان في الجلد لتنشيط الالوان، وبتستخدم دراعاتها في التزاوج، وبتستخدم حبرها في التمويه، وبتستخدم العقلية في حل اللغز، وبتستخدم القدرة على التعلم من خلال المشاهدة.

[Source: الأخطبوط  الدحيح | Rank: 1]

In [22]:
# from llm_client_openai import OpenAILLM
# from prompts import build_strict_grounded_prompt

# # Initialize OpenAI model
# llm = OpenAILLM(model_name="gpt-3.5-turbo")

# # User query
# query = "الأخطبوط ذكي ازاي؟"

# # Retrieve relevant chunks
# retrieved_chunks = retriever.retrieve(query)

# # Build grounded prompt
# prompt = build_strict_grounded_prompt(
#     question=query,
#     retrieved_chunks=retrieved_chunks
# )

# # Generate answer
# answer = llm.generate(prompt)

# print(answer)

In [23]:
# HuggingFace
from llm_client_hf import HuggingFaceLLM
from prompts import build_strict_grounded_prompt

hf_llm = HuggingFaceLLM(
    model_name="Qwen/Qwen2.5-7B-Instruct"
)

query = "ليه دم الأخطبوط أزرق؟"

retrieved_chunks = retriever.retrieve(query)

print("========== RETRIEVED CONTEXT ==========\n")

for chunk in retrieved_chunks:
    distance = chunk["distance"]

    # Convert distance to relevance score
    relevance_score = 1 / (1 + distance)

    print(f"Rank: {chunk['rank']}")
    print(f"Episode: {chunk['episode']}")
    print(f"Distance: {distance}")
    print(f"Relevance Score: {relevance_score:.4f}")
    print("-" * 50)
    print(chunk["text"])
    print("\n" + "=" * 70 + "\n")

prompt = build_strict_grounded_prompt(
    question=query,
    retrieved_chunks=retrieved_chunks
)

print("\n\n========== FINAL PROMPT SENT TO MODEL ==========\n")
print(prompt)

answer = hf_llm.generate(prompt)

print("\n\n========== MODEL ANSWER ==========\n")
print(answer)

========== RETRIEVED CONTEXT ==========

Rank: 1
Episode: الأخطبوط  الدحيح
Distance: 0.9826875925064087
Relevance Score: 0.5044
--------------------------------------------------
اخطبوط بينزف، هتلاقي ان دمه لونه مش زينا، دم الاخطبوط لونه ازرق. اللي بيخلي دمنا لونه احمر، هو بروتين اسمه الهيموجلوبين، ولكن لان الاخطبوط بيعيش في بيئات صعبة، ساعات، يعيش في ميه دافية، ساعات، يعيش في بيئة تحت الصفر، فلم يكتف بوجود الهيموجلوبين بس، عنده بروتين، يا عزيزي، اسمه هيموسيانين، دا بيبقي مبني علي النحاس، وتلاقيه بيمسك الاكسجين احسن من الهيموجلوبين. ولكن Actually، اللي بيميز الاخطبوط عن معظم الرخويات مش كل الحاجات الغريبة، اللي حكيتلك عنها دي، لا ال3 قلوب ولا الدم الازرق، ولا كل دا، ولكن اللي بيميزه، يا عزيزي، ان هو ما عندهوش صدفة تحميه، الاخطبوط ماشي سلبوتة، عريان! ودا شيء عجيب، لان انت لو جيت بصيت علي الرخويات، هتلاقي ان دا خط الدفاع الاساسي ليهم، بص لابن عمه مثلا، النوتيلوس، بيخش في صدفة، زي السلحفاة، متقسمة لاوض، عشان تقدر توزع الضغط، فيبقي صعب ان هذه الصدفة تتكسر. الاخطبوط بقي، يا عزيزي، ما عندهوش اي حماية جسدية، ما عندهوش حتي مخالب، ودا بيخليه، بسم الله، ما شاء الله، فريسة لقطة، واسال البرتغاليين، بيحطوه علي الرز، وبالهنا والشفا! لا فيه عضم ولا صدف، بالعكس، دا نسبة البروتين في بعض الانواع بتوصل ل35%، دا غير طبعا الاحماض الدهنية المهمة والفيتامينات والمعادن، فانت عندك، بسم الله، ما شاء الله، Protein Shake متحرك! كل المفترسين عينيهم علي الوجبة دي، القرش، الهامور، الفقمة، الحيتان، تعالب الميه، البطاريق. انت متخيل، يا عزيزي، كائن البطريق بيفترسه! الطيور كمان بتاكل الاخطبوط. لو جيت، يا عزيزي، بصيت في كل الحاجات دي، تتوقع ان الكائن دا المفروض ينقرض بسرعة، هو قاعد ازاي لحد دلوقتي؟! ولكن تيجي تبص، تلاقي ان الاخطبوط بانواعه ال300 مالي كل حتة تقريبا في العالم، من السواحل لاعمق نقط في المحيط، الاماكن اللي ما بيوصلهاش نور، ومن اكبرهم، الGiant Pacific Octopus، لاصغرهم، الOctopus Wolfi، دا، يا عزيزي، اخطبوط اقل من جرام! اهو الحيوان قليل الحيلة دا، بقي من انجح افراد عيلته، جرام! لو جيت تاملت، هتجد ان المفارقة يمكن تكون ان الاخطبوط نجح بسبب قلة حيلته. الاخطبوط كائن لين، عشان كدا، سجله الاحفوري، لما تيجي تبص بقي في الحفريات، ما تلاقيهوش اوي، التحفر بيتطلب ان الكائن يتحفظ قبل ما الانسجة تتحلل، فالاجزاء الصلبة، زي الصدف او العضم مثلا، بيبقي عندها فرصة احسن انها تتحول الي

======================================================================

Rank: 2
Episode: الأخطبوط  الدحيح
Distance: 1.085485816001892
Relevance Score: 0.4795
--------------------------------------------------
يا عزيزي، اخطبوط اقل من جرام! اهو الحيوان قليل الحيلة دا، بقي من انجح افراد عيلته، جرام! لو جيت تاملت، هتجد ان المفارقة يمكن تكون ان الاخطبوط نجح بسبب قلة حيلته. الاخطبوط كائن لين، عشان كدا، سجله الاحفوري، لما تيجي تبص بقي في الحفريات، ما تلاقيهوش اوي، التحفر بيتطلب ان الكائن يتحفظ قبل ما الانسجة تتحلل، فالاجزاء الصلبة، زي الصدف او العضم مثلا، بيبقي عندها فرصة احسن انها تتحول الي حفريات، فالعلماء ييجوا يدرسوها، ويعرفوا اكتر عن هذا الكائن، وتطوره عبر التاريخ. لكن الحيوانات، اللي ما عندهاش اجزاء صلبة كدا، بنلاقيها قليلة اوي في السجل الاحفوري. بس هل دا معناه ان العلماء ما لقوش تاريخ للاخطبوط؟ لا، بالعكس، لقوا حفريات لاسلاف الاخطبوط زي المجموعة دي... معلش، تلاقيني، يا عزيزي، في الاحفوري مش اد كدا! المجموعة دي، لقوا فيها حاجة غريبة جدا، لقوا فيها بقايا صدفة، دا، بشكل او باخر، بيدل ان الاخطبوط زمان كان عنده صدفة، بالظبط زي معظم الرخويات، ولكنه مع الوقت فقدها. في 2015، هيتم نشر دراسة ضخمة في مجلة Nature، اول خريطة جينية كاملة للاخطبوط، وبربط بقي الادلة بتاعة الحفريات والتشريح والتحليل الجيني، هنعرف ان اسلاف الاخطبوط، اجداد الاخطبوط، كانت كائنات بطيئة وبسيطة، جسمها ناعم، وعليه صدفة زي المحار، الصدفة دي بتحميهم وهما بيزحفوا في القاع، في قاع المحيط. بعد كدا، مع الوقت، هنشوف في العصر الطباشيري هتبدا تختفي الصدفة دي، ما عادتش تبقي موجودة. علي حسب بحث اسمه Shell Loss in Cephalopods، فقدان الصدفة الخارجية اللي كانت عند الاخطبوط في وقت من الاوقات دي سببه ان الكائنات كانت محتاجة حرية اكبر، مرونة اكتر، ليه؟ عشان تقدر تهرب من المفترسين، وتتحرك بقي من القاع، تطلع فوق، تنزل تحت، تتحرك براحتها. وفي دراسة تانية اسمها Evolution of Predator Avoidance in Cephalopods، بتقول ان التطور دا تحديدا حصل لما ابتدت تظهر الاسماك المفترسة، وقتها، معظم اللافقاريات اعتمدت علي انها تبقي عندها سم او درع او شوك، ولكن بقي راسيات الارجل، زي الاخطبوط مثلا، قالك: "انا هاعمل دفاعيات اذكي واعقد." هتعمل ايه يا اخطبوط يا ابن اللذين؟! "اول حاجة، هاموه، هارقص الPredator." لما الاخطبوط بيحس بخطر، بيتحول لحجر مرمي متغطي بالشعب المرجانية، ودا، يا عزيزي، بيحصل في ايه؟ في ثواني، ولا تاخد بالك! السر الحقيقي في جلده، جلده اللي فيه

======================================================================

Rank: 3
Episode: الأخطبوط  الدحيح
Distance: 1.116047739982605
Relevance Score: 0.4726
--------------------------------------------------
بيعمله قوام، عشان يبقي 3D كدا، ومادة اسمها "تيروسينيز"، دي، يا عزيزي، بتخش علي حواس الشم والتذوق عند المفترس، تلخبط امه! وخصوصا، خصوصا، القروش، بيبقي القرش لا شايفه ولا حاسس بيه! انا عايز اقولك، يا عزيزي، ان المادة دي مربكة لدرجة ان الاخطبوط نفسه ليس محصن ضدها، لو اتحبس في حوض ما بيتنضفش ويت"فلتر"، ممكن يموت نفسه! "طب يا (ابو حميد)، لو الحبر دا خلص، مش المفترس دا ممكن يشوفه تاني، ويرجع ياكله؟" هنا بقي، يا عزيزي، بييجي دور اطلاق الصاروخ، في جسم الاخطبوط، فيه تجويف عضلي بفتحة، بيقوم ساحب فيه الميه، ويقفل الفتحة دي، ويقوم مخرجها بقوة من فتحة الSiphon الضيقة بتاعته، فيهرب، يا عزيزي، بطريقة الدفع النفاث، Jet Propulsion، زي ان انت تنفخ بالونة كدا، وتسيبها تطير فجاة...! الفرق بقي ان الاخطبوط بيقدر يوجه النفاث دا يمين او شمال، فانت عندك الF-35! دا، يا عزيزي، في حالة الخطر. طيب، لما الدنيا بتبقي هادية، الاخطبوط بيعمل ايه؟ حياته ما بتبقاش هادية كدا؟ ما بتبقاش طبيعية؟ كل حياته خطر ومطاردات؟ لا، يا عزيزي، عادي، احيانا، الدنيا بتبقي هادية خالص، والاخطبوط بيعوم في الميه زي الفل، ولكنه، عشان اكون صريح معاك، لا يحب السباحة، بيحب يتمشي علي القاع بدراعاته. "الله! طب ثانية واحدة يا (ابو حميد)، هو ازاي بيمشي، وهو ما عندهوش عضم؟! دا، يا عزيزي، طبعا سؤال ساذج، انا كنت عايزك تساله، عشان اكلمك علي دراعات الاخطبوط. علي حسب الدكتورة "ميلينا هيل" عالمة الاحياء في جامعة "شيكاغو"، غياب الهيكل العظمي للاخطبوط اتعوض ببنية عضلية اسمها Hydrostat عضلي، بمعني ان كل دراع بيبقي عنده Level من الصلابة، كل دراع فيه عضلات بالعرض بتديله صلابة، وعضلات بالطول تطول وتقصر الدراع، وعضلات حلزونية تخليه يلتوي، وجوا هذه العضلات هناك حبل عصبي متموج، عشان لو الدراع طول او قصر، ما يحصلش اي تاثير، "انا لسة قادر اControl، ما فيش مشاكل!" لان الاعصاب ما بتتمطش، زي الاوعية الدموية كدا. بص، يا عزيزي، علي دراعك، هناك كام مفصل؟ انت عندك 3 مفاصل اساسية، ال3 مفاصل دول بيدوك 7 درجات من الحرية، الكتف بيدي 3، فوق، تحت، قدام، ورا، حوالين المحور. الكوع حركة واحدة، تني وامتداد. الWrist حركتين، فوق، تحت، ويمين، شمال. دراع الاخطبوط بقي، يا عزيزي، يا اللي فرحان بمفاصلك، بيعمل مفاصل زائفة، يقدر بقي يعمل

======================================================================

Rank: 4
Episode: الأخطبوط  الدحيح
Distance: 1.2244879007339478
Relevance Score: 0.4495
--------------------------------------------------
الاخطبوط هنا ما اخترعش الية جديدة، هو اعاد توظيف الية موجودة، بس في حتة تانية، ودي بالظبط عبقرية الاخطبوط، هو مش كائن فضائي، ما عندهوش اليات خارقة، ولكن ترتيبة جسمه استثنائية. بس خد بالك، التمويه دا ليس مجاني، في تجربة اتعملت علي الاخطبوط الياقوتي الشرقي، سلطوا ضوء ازرق، عشان ينشط خلايا الالوان، وقاموا عاملين مقارنة، والمقارنة هتعتمد علي استهلاك الاكسجين قبل وبعد التنشيط، هنشوف بيستهلك اكسجين اد ايه لما ينشط، عشان يقدروا يحسبوا الCalories، الطاقة اللي بيتم استخدامها في حاجة زي كدا. وجدوا، يا عزيزي، ان جهاز التمويه دا، اللي هو شوية خلايا صغيرة في الجلد، بتستهلك اد باقي الجسم كله، انت بتتكلم هنا علي المخ والاعضاء والدراعات، كل دا، يا عزيزي، من غير ما احط في الحسبة الملمس بتاع الجلد، فانت مش بس نظري، انت كمان Texture. فغالبا، الاخطبوط بيستهلك طاقة، عشان يقدر يموه اكتر من اي حيوان. عشان كدا، احسن حاجة يعملها هي انه يهرب، ودا برضه، عنده Technique فيه. الاخطبوط عنده عضو اسمه كيس الحبر، دا موجود جنب الجهاز الهضمي والمثانة، فيه غدد بتعمل الحبر، وقت الخطر، الاخطبوط بيقوم قابض عضلاته، فيخرج الحبر لبرة من فتحة اسمها Siphon، الحبر دا لما بيخرج، بيخرج في صورة سحابة سودا كثيفة، احيانا، بتكون زي فقاقيع كدا، فتعمل، زي ما تكون، تماثيل وهمية منه، "انا رحت كدا"، "انا رحت كدا." او ممكن تبقي السحابة كتلة واحدة كبيرة، لحد ما هو يعرف يهرب، فانت تبقي عميت المفترس، اجري انت بقي، يلا، استخبي! "واضح يا (ابو حميد) ان انت بقالك مختفي فترة عن عالم الافتراس، الحيوانات يا (ابو حميد) مش بتعتمد علي النظر اوي، ممكن تعتمد علي الشم، ممكن تعتمد علي الاحساس بالحركة." خليني، يا عزيزي، اقولك ان دا مش اي حبر، الحبر دا بيتكون من 3 مكونات اساسية، ميلانين، بيديله لون، مخاط بيعمله قوام، عشان يبقي 3D كدا، ومادة اسمها "تيروسينيز"، دي، يا عزيزي، بتخش علي حواس الشم والتذوق عند المفترس، تلخبط امه! وخصوصا، خصوصا، القروش، بيبقي القرش لا شايفه ولا حاسس بيه! انا عايز اقولك، يا عزيزي، ان المادة دي مربكة لدرجة ان الاخطبوط نفسه ليس محصن ضدها، لو اتحبس في حوض ما بيتنضفش ويت"فلتر"، ممكن يموت نفسه! "طب يا (ابو حميد)، لو الحبر دا خلص، مش المفترس دا ممكن يشوفه

======================================================================

Rank: 5
Episode: الأخطبوط  الدحيح
Distance: 1.2343270778656006
Relevance Score: 0.4476
--------------------------------------------------
نتوءات صغيرة، عشان الملمس يبقي كان انت واقف علي صخور، كان انت بتشوف شعب مرجانية. بعض الانواع، زي الاخطبوط المقلد، لو قابل مفترس، زي الDamselfish، بيغير، يا عزيزي، شكله بالكامل، بيبقي عارف ايه؟ ممكن يعمل نفسه تعبان بحر، اللي هو المفترس الطبيعي للDamsel! وقدام كل مفترس، ممكن يتحول الي سمكة الاسد، او سمكة موسي، دا غير انه يقدر يتحول ل15 مخلوق تاني، فانت، يا عزيزي، مش معاك كائن، انت معاك Technology تتحولك ل15 كائن تاني! وسط الكائنات، يا عزيزي، كل ما كانت الوانك فاقعة، زاهية اوي، كل ما انت غالبا كنت سام، فالاخطبوط ممكن يلعب برضه بالحيلة دي، ممكن يبقي الوانه زاهية اكتر، بحيث ان المفترس لما يشوفهولك، يقولك: "اه! لا، لا، لا، اوعي تاكل من البتاع دا! دا ممكن يبقي سام." بيلعب في الوانه. الاخطبوط، مثلا، ازرق الخطوط، دا اخطبوط صغير، 15 سم بس، بس جوا سم بيقتل البشر والحيوانات، لما بيستفز، بتظهر علي جسمه حلقات زرقا بتلمع، رسالة واضحة للمفترس: "ما تجيش هنا، والا هازعل امك!" كل دا، يا عزيزي، جميل ومبهر، لحد ما الابحاث الجديدة بتكتشف شيء مذهل، عين الاخطبوط فيها بروتينات حساسة للضوء اسمها Rhodoposins، ولكن فيها نوع واحد من مستقبلات الضوء، بالتالي، يا عزيزي، الاخطبوط علي الAction والالوان والتحولات لاسماك مختلفة، Actually، عنده عمي الوان، او بيشوف ابيض واسود. "يا نهار اسود يا (ابو حميد)! يعني، بيخلي لون جسمه يتغير لالوان مختلفة، ويعمل لوح فنية، وفي الاخر، ما بيشوفش؟! ما بيشوفش الوان؟!" باحثين في جامعة "كاليفورنيا" هياخدوا شرايح من جلد... ويقوموا، يا عزيزي، مسلطين عليها ضوء، فيتفاجئوا ان الصبغات بتنتشر وترد علي الضوء، بيكتشفوا ان جلد الاخطبوط عنده بروتينات حساسة للضوء، من نفس عيلة البروتين اللي موجودة في العين عنده، كان جلد الاخطبوط، زي ما تقول كدا، بيشوف هو كمان. الباحث "تود اوكلي" بيقول ان الاخطبوط هنا ما اخترعش الية جديدة، هو اعاد توظيف الية موجودة، بس في حتة تانية، ودي بالظبط عبقرية الاخطبوط، هو مش كائن فضائي، ما عندهوش اليات خارقة، ولكن ترتيبة جسمه استثنائية. بس خد بالك، التمويه دا ليس مجاني، في تجربة اتعملت علي الاخطبوط الياقوتي الشرقي، سلطوا ضوء ازرق، عشان ينشط خلايا الالوان، وقاموا عاملين مقارنة، والمقارنة هتعتمد علي استهلاك الاكسجين قبل وبعد التنشيط، هنشوف بيستهلك اكسجين اد ايه لما ينشط،

======================================================================



========== FINAL PROMPT SENT TO MODEL ==========

You are an Arabic question-answering assistant.

You must answer using ONLY the provided context.

Rules:
1. Do not use outside knowledge.
2. If the answer is not clearly found in the context, say:
   "لا توجد معلومات كافية في النص للإجابة عن هذا السؤال."
3. Answer in the same language as the user's question.
4. If the question mixes Arabic and English, you may answer in Arabic with necessary English terms.
5. Keep the answer clear and concise.
6. Mention the source episode name at the end.

Retrieved context:
[Source: الأخطبوط  الدحيح | Rank: 1]
اخطبوط بينزف، هتلاقي ان دمه لونه مش زينا، دم الاخطبوط لونه ازرق. اللي بيخلي دمنا لونه احمر، هو بروتين اسمه الهيموجلوبين، ولكن لان الاخطبوط بيعيش في بيئات صعبة، ساعات، يعيش في ميه دافية، ساعات، يعيش في بيئة تحت الصفر، فلم يكتف بوجود الهيموجلوبين بس، عنده بروتين، يا عزيزي، اسمه هيموسيانين، دا بيبقي مبني علي النحاس، وتلاقيه بيمسك الاكسجين احسن من الهيموجلوبين. ولكن Actually، اللي بيميز الاخطبوط عن معظم الرخويات مش كل الحاجات الغريبة، اللي حكيتلك عنها دي، لا ال3 قلوب ولا الدم الازرق، ولا كل دا، ولكن اللي بيميزه، يا عزيزي، ان هو ما عندهوش صدفة تحميه، الاخطبوط ماشي سلبوتة، عريان! ودا شيء عجيب، لان انت لو جيت بصيت علي الرخويات، هتلاقي ان دا خط الدفاع الاساسي ليهم، بص لابن عمه مثلا، النوتيلوس، بيخش في صدفة، زي السلحفاة، متقسمة لاوض، عشان تقدر توزع الضغط، فيبقي صعب ان هذه الصدفة تتكسر. الاخطبوط بقي، يا عزيزي، ما عندهوش اي حماية جسدية، ما عندهوش حتي مخالب، ودا بيخليه، بسم الله، ما شاء الله، فريسة لقطة، واسال البرتغاليين، بيحطوه علي الرز، وبالهنا والشفا! لا فيه عضم ولا صدف، بالعكس، دا نسبة البروتين في بعض الانواع بتوصل ل35%، دا غير طبعا الاحماض الدهنية المهمة والفيتامينات والمعادن، فانت عندك، بسم الله، ما شاء الله، Protein Shake متحرك! كل المفترسين عينيهم علي الوجبة دي، القرش، الهامور، الفقمة، الحيتان، تعالب الميه، البطاريق. انت متخيل، يا عزيزي، كائن البطريق بيفترسه! الطيور كمان بتاكل الاخطبوط. لو جيت، يا عزيزي، بصيت في كل الحاجات دي، تتوقع ان الكائن دا المفروض ينقرض بسرعة، هو قاعد ازاي لحد دلوقتي؟! ولكن تيجي تبص، تلاقي ان الاخطبوط بانواعه ال300 مالي كل حتة تقريبا في العالم، من السواحل لاعمق نقط في المحيط، الاماكن اللي ما بيوصلهاش نور، ومن اكبرهم، الGiant Pacific Octopus، لاصغرهم، الOctopus Wolfi، دا، يا عزيزي، اخطبوط اقل من جرام! اهو الحيوان قليل الحيلة دا، بقي من انجح افراد عيلته، جرام! لو جيت تاملت، هتجد ان المفارقة يمكن تكون ان الاخطبوط نجح بسبب قلة حيلته. الاخطبوط كائن لين، عشان كدا، سجله الاحفوري، لما تيجي تبص بقي في الحفريات، ما تلاقيهوش اوي، التحفر بيتطلب ان الكائن يتحفظ قبل ما الانسجة تتحلل، فالاجزاء الصلبة، زي الصدف او العضم مثلا، بيبقي عندها فرصة احسن انها تتحول الي

---

[Source: الأخطبوط  الدحيح | Rank: 2]
يا عزيزي، اخطبوط اقل من جرام! اهو الحيوان قليل الحيلة دا، بقي من انجح افراد عيلته، جرام! لو جيت تاملت، هتجد ان المفارقة يمكن تكون ان الاخطبوط نجح بسبب قلة حيلته. الاخطبوط كائن لين، عشان كدا، سجله الاحفوري، لما تيجي تبص بقي في الحفريات، ما تلاقيهوش اوي، التحفر بيتطلب ان الكائن يتحفظ قبل ما الانسجة تتحلل، فالاجزاء الصلبة، زي الصدف او العضم مثلا، بيبقي عندها فرصة احسن انها تتحول الي حفريات، فالعلماء ييجوا يدرسوها، ويعرفوا اكتر عن هذا الكائن، وتطوره عبر التاريخ. لكن الحيوانات، اللي ما عندهاش اجزاء صلبة كدا، بنلاقيها قليلة اوي في السجل الاحفوري. بس هل دا معناه ان العلماء ما لقوش تاريخ للاخطبوط؟ لا، بالعكس، لقوا حفريات لاسلاف الاخطبوط زي المجموعة دي... معلش، تلاقيني، يا عزيزي، في الاحفوري مش اد كدا! المجموعة دي، لقوا فيها حاجة غريبة جدا، لقوا فيها بقايا صدفة، دا، بشكل او باخر، بيدل ان الاخطبوط زمان كان عنده صدفة، بالظبط زي معظم الرخويات، ولكنه مع الوقت فقدها. في 2015، هيتم نشر دراسة ضخمة في مجلة Nature، اول خريطة جينية كاملة للاخطبوط، وبربط بقي الادلة بتاعة الحفريات والتشريح والتحليل الجيني، هنعرف ان اسلاف الاخطبوط، اجداد الاخطبوط، كانت كائنات بطيئة وبسيطة، جسمها ناعم، وعليه صدفة زي المحار، الصدفة دي بتحميهم وهما بيزحفوا في القاع، في قاع المحيط. بعد كدا، مع الوقت، هنشوف في العصر الطباشيري هتبدا تختفي الصدفة دي، ما عادتش تبقي موجودة. علي حسب بحث اسمه Shell Loss in Cephalopods، فقدان الصدفة الخارجية اللي كانت عند الاخطبوط في وقت من الاوقات دي سببه ان الكائنات كانت محتاجة حرية اكبر، مرونة اكتر، ليه؟ عشان تقدر تهرب من المفترسين، وتتحرك بقي من القاع، تطلع فوق، تنزل تحت، تتحرك براحتها. وفي دراسة تانية اسمها Evolution of Predator Avoidance in Cephalopods، بتقول ان التطور دا تحديدا حصل لما ابتدت تظهر الاسماك المفترسة، وقتها، معظم اللافقاريات اعتمدت علي انها تبقي عندها سم او درع او شوك، ولكن بقي راسيات الارجل، زي الاخطبوط مثلا، قالك: "انا هاعمل دفاعيات اذكي واعقد." هتعمل ايه يا اخطبوط يا ابن اللذين؟! "اول حاجة، هاموه، هارقص الPredator." لما الاخطبوط بيحس بخطر، بيتحول لحجر مرمي متغطي بالشعب المرجانية، ودا، يا عزيزي، بيحصل في ايه؟ في ثواني، ولا تاخد بالك! السر الحقيقي في جلده، جلده اللي فيه

---

[Source: الأخطبوط  الدحيح | Rank: 3]
بيعمله قوام، عشان يبقي 3D كدا، ومادة اسمها "تيروسينيز"، دي، يا عزيزي، بتخش علي حواس الشم والتذوق عند المفترس، تلخبط امه! وخصوصا، خصوصا، القروش، بيبقي القرش لا شايفه ولا حاسس بيه! انا عايز اقولك، يا عزيزي، ان المادة دي مربكة لدرجة ان الاخطبوط نفسه ليس محصن ضدها، لو اتحبس في حوض ما بيتنضفش ويت"فلتر"، ممكن يموت نفسه! "طب يا (ابو حميد)، لو الحبر دا خلص، مش المفترس دا ممكن يشوفه تاني، ويرجع ياكله؟" هنا بقي، يا عزيزي، بييجي دور اطلاق الصاروخ، في جسم الاخطبوط، فيه تجويف عضلي بفتحة، بيقوم ساحب فيه الميه، ويقفل الفتحة دي، ويقوم مخرجها بقوة من فتحة الSiphon الضيقة بتاعته، فيهرب، يا عزيزي، بطريقة الدفع النفاث، Jet Propulsion، زي ان انت تنفخ بالونة كدا، وتسيبها تطير فجاة...! الفرق بقي ان الاخطبوط بيقدر يوجه النفاث دا يمين او شمال، فانت عندك الF-35! دا، يا عزيزي، في حالة الخطر. طيب، لما الدنيا بتبقي هادية، الاخطبوط بيعمل ايه؟ حياته ما بتبقاش هادية كدا؟ ما بتبقاش طبيعية؟ كل حياته خطر ومطاردات؟ لا، يا عزيزي، عادي، احيانا، الدنيا بتبقي هادية خالص، والاخطبوط بيعوم في الميه زي الفل، ولكنه، عشان اكون صريح معاك، لا يحب السباحة، بيحب يتمشي علي القاع بدراعاته. "الله! طب ثانية واحدة يا (ابو حميد)، هو ازاي بيمشي، وهو ما عندهوش عضم؟! دا، يا عزيزي، طبعا سؤال ساذج، انا كنت عايزك تساله، عشان اكلمك علي دراعات الاخطبوط. علي حسب الدكتورة "ميلينا هيل" عالمة الاحياء في جامعة "شيكاغو"، غياب الهيكل العظمي للاخطبوط اتعوض ببنية عضلية اسمها Hydrostat عضلي، بمعني ان كل دراع بيبقي عنده Level من الصلابة، كل دراع فيه عضلات بالعرض بتديله صلابة، وعضلات بالطول تطول وتقصر الدراع، وعضلات حلزونية تخليه يلتوي، وجوا هذه العضلات هناك حبل عصبي متموج، عشان لو الدراع طول او قصر، ما يحصلش اي تاثير، "انا لسة قادر اControl، ما فيش مشاكل!" لان الاعصاب ما بتتمطش، زي الاوعية الدموية كدا. بص، يا عزيزي، علي دراعك، هناك كام مفصل؟ انت عندك 3 مفاصل اساسية، ال3 مفاصل دول بيدوك 7 درجات من الحرية، الكتف بيدي 3، فوق، تحت، قدام، ورا، حوالين المحور. الكوع حركة واحدة، تني وامتداد. الWrist حركتين، فوق، تحت، ويمين، شمال. دراع الاخطبوط بقي، يا عزيزي، يا اللي فرحان بمفاصلك، بيعمل مفاصل زائفة، يقدر بقي يعمل

---

[Source: الأخطبوط  الدحيح | Rank: 4]
الاخطبوط هنا ما اخترعش الية جديدة، هو اعاد توظيف الية موجودة، بس في حتة تانية، ودي بالظبط عبقرية الاخطبوط، هو مش كائن فضائي، ما عندهوش اليات خارقة، ولكن ترتيبة جسمه استثنائية. بس خد بالك، التمويه دا ليس مجاني، في تجربة اتعملت علي الاخطبوط الياقوتي الشرقي، سلطوا ضوء ازرق، عشان ينشط خلايا الالوان، وقاموا عاملين مقارنة، والمقارنة هتعتمد علي استهلاك الاكسجين قبل وبعد التنشيط، هنشوف بيستهلك اكسجين اد ايه لما ينشط، عشان يقدروا يحسبوا الCalories، الطاقة اللي بيتم استخدامها في حاجة زي كدا. وجدوا، يا عزيزي، ان جهاز التمويه دا، اللي هو شوية خلايا صغيرة في الجلد، بتستهلك اد باقي الجسم كله، انت بتتكلم هنا علي المخ والاعضاء والدراعات، كل دا، يا عزيزي، من غير ما احط في الحسبة الملمس بتاع الجلد، فانت مش بس نظري، انت كمان Texture. فغالبا، الاخطبوط بيستهلك طاقة، عشان يقدر يموه اكتر من اي حيوان. عشان كدا، احسن حاجة يعملها هي انه يهرب، ودا برضه، عنده Technique فيه. الاخطبوط عنده عضو اسمه كيس الحبر، دا موجود جنب الجهاز الهضمي والمثانة، فيه غدد بتعمل الحبر، وقت الخطر، الاخطبوط بيقوم قابض عضلاته، فيخرج الحبر لبرة من فتحة اسمها Siphon، الحبر دا لما بيخرج، بيخرج في صورة سحابة سودا كثيفة، احيانا، بتكون زي فقاقيع كدا، فتعمل، زي ما تكون، تماثيل وهمية منه، "انا رحت كدا"، "انا رحت كدا." او ممكن تبقي السحابة كتلة واحدة كبيرة، لحد ما هو يعرف يهرب، فانت تبقي عميت المفترس، اجري انت بقي، يلا، استخبي! "واضح يا (ابو حميد) ان انت بقالك مختفي فترة عن عالم الافتراس، الحيوانات يا (ابو حميد) مش بتعتمد علي النظر اوي، ممكن تعتمد علي الشم، ممكن تعتمد علي الاحساس بالحركة." خليني، يا عزيزي، اقولك ان دا مش اي حبر، الحبر دا بيتكون من 3 مكونات اساسية، ميلانين، بيديله لون، مخاط بيعمله قوام، عشان يبقي 3D كدا، ومادة اسمها "تيروسينيز"، دي، يا عزيزي، بتخش علي حواس الشم والتذوق عند المفترس، تلخبط امه! وخصوصا، خصوصا، القروش، بيبقي القرش لا شايفه ولا حاسس بيه! انا عايز اقولك، يا عزيزي، ان المادة دي مربكة لدرجة ان الاخطبوط نفسه ليس محصن ضدها، لو اتحبس في حوض ما بيتنضفش ويت"فلتر"، ممكن يموت نفسه! "طب يا (ابو حميد)، لو الحبر دا خلص، مش المفترس دا ممكن يشوفه

---

[Source: الأخطبوط  الدحيح | Rank: 5]

Full Rag Pipeline Call

In [24]:
from rag_pipeline_ import RAGPipeline
from llm_client_openai import OpenAILLM

# llm = OpenAILLM(model_name="gpt-3.5-turbo")
GroqLLM(model_name="llama-3.1-8b-instant")

rag = RAGPipeline(
    retriever=retriever,
    llm=llm,
    prompt_type="strict"
)

result = rag.answer("الأخطبوط ذكي ازاي؟")

print(result["answer"])
print(result["model"])

الأخطبوط ذكي لانة بتستخدم الية موجودة في جسمها بطريقة استثنائية، زي مثلا استخدام بروتينات حساسة للضوء في جلدها، وبتستخدمها في التمويه والتحويل لالوان مختلفة. وبتستخدم أيضا دراعاتها في التزاوج والتعاون مع انواع تانية من الحيوانات.

 Source: الأخطبوط  الدحيح | Rank: 1
llama-3.1-8b-instant

In [25]:
# Using Arabic prompt test
rag_arabic = RAGPipeline(
    retriever=retriever,
    llm=llm,
    prompt_type="arabic"
)

result = rag_arabic.answer("الأخطبوط ذكي ازاي؟")
print(result["answer"])

الأخطبوط ذكي لانة بتستخدم الية موجودة في جسمها لتحقيق التمويه والتحول لاسماك مختلفة، وبتستخدم بروتينات حساسة للضوء في جلدها لتشعشعة الضوء وتغير لون جسمها، وبتستخدم دراعاتها لتحقيق التعلم الاجتماعي والتعاون مع انواع تانية. (الأخطبوط الدحيح | Rank: 5)

Langchain - Augment Rag with memory

In [26]:
from conversation_memory import ConversationMemory

memory = ConversationMemory()

memory.add_user_message("الأخطبوط ذكي ازاي؟")
memory.add_ai_message("الأخطبوط ذكي بسبب قدرته على التمويه والتعلم.")

print(memory.get_full_history_text())

User: الأخطبوط ذكي ازاي؟
Assistant: الأخطبوط ذكي بسبب قدرته على التمويه والتعلم.

In [27]:
# from conversation_memory import ConversationMemory
# from rag_pipeline_ import RAGPipeline
# from llm_client_openai import OpenAILLM

# memory = ConversationMemory()
# llm = OpenAILLM(model_name="gpt-3.5-turbo")

# rag = RAGPipeline(
#     retriever=retriever,
#     llm=llm,
#     prompt_type="strict",
#     memory=memory,
#     use_memory=True
# )

# result1 = rag.answer("الأخطبوط ذكي ازاي؟")
# print(result1["answer"])

# result2 = rag.answer("طب هو بيستخدم الحبر ليه؟")
# print(result2["answer"])

# print("\nMEMORY:")
# print(memory.get_full_history_text())

Memory / Context Window Strategies

A) Full history

In [28]:
memory_full = ConversationMemory()

rag_full = RAGPipeline(
    retriever=retriever,
    llm=llm,
    prompt_type="strict",
    memory=memory_full,
    use_memory=True,
    memory_strategy="full"
)

print(rag_full.answer("الأخطبوط ذكي ازاي؟")["answer"])
print(rag_full.answer("طب هو بيستخدم الحبر ليه؟")["answer"])

print("Prompt chars:", rag_full.answer("وقدرته على التمويه ازاي؟")["prompt_chars"])

الأخطبوط ذكي لانها بتستخدم الية موجودة في جسمها، مثل خلايا الالوان والبروتينات الحساسة للضوء، لتحقيق التمويه والتحولات في لون جسمها. كمان، الاخطبوط بتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة، وبتستخدم العقلية اللاعقلانية في حل المشكلات.

الأخطبوط كمان بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية ال
السؤال خارج نطاق المحتوى المتاح.
Prompt chars: 0

In [29]:
print("\nMEMORY:")
print(memory_full.get_full_history_text())

MEMORY:
User: الأخطبوط ذكي ازاي؟
Assistant: الأخطبوط ذكي لانها بتستخدم الية موجودة في جسمها، مثل خلايا الالوان والبروتينات الحساسة للضوء، لتحقيق التمويه والتحولات في لون جسمها. كمان، الاخطبوط بتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة، وبتستخدم العقلية اللاعقلانية في حل المشكلات.

الأخطبوط كمان بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية اللاعقلانية في حل المشكلات، مثل حل اللغز والتحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم تقنياتها في التمويه، مثل استخدام الحبر لخداع المفترس، وبتستخدم مهاراتها في التحكم في الحركة والتحول لاسماك مختلفة.

الأخطبوط بتستخدم العقلية ال

B) Sliding window

In [30]:
memory_sliding = ConversationMemory()

rag_sliding = RAGPipeline(
    retriever=retriever,
    llm=llm,
    prompt_type="strict",
    memory=memory_sliding,
    use_memory=True,
    memory_strategy="sliding",
    last_n_turns=1
)

print(rag_sliding.answer("الأخطبوط ذكي ازاي؟")["answer"])
print(rag_sliding.answer("طب هو بيستخدم الحبر ليه؟")["answer"])

print("Prompt chars:", rag_sliding.answer("وقدرته على التمويه ازاي؟")["prompt_chars"])

الأخطبوط ذكي لانة بتستخدم الية موجودة في جسمها بطريقة استثنائية، زي مثلا استخدام بروتينات حساسة للضوء في جلدها، وبتستخدمها لتخفيض الالوان وتحويلها، وبتستخدمها كذلك لتخفيض الالوان وتحويلها، وبتستخدمها كذلك لتخفيض الالوان وتحويلها.

(الأخطبوط الدحيح | Rank: 1)
السؤال خارج نطاق المحتوى المتاح.
Prompt chars: 0

C) Strict truncation

In [31]:
memory_truncated = ConversationMemory()

rag_truncated = RAGPipeline(
    retriever=retriever,
    llm=llm,
    prompt_type="strict",
    memory=memory_truncated,
    use_memory=True,
    memory_strategy="truncated",
    max_history_chars=1000
)

print(rag_truncated.answer("الأخطبوط ذكي ازاي؟")["answer"])
print(rag_truncated.answer("طب هو بيستخدم الحبر ليه؟")["answer"])

print("Prompt chars:", rag_truncated.answer("وقدرته على التمويه ازاي؟")["prompt_chars"])

الأخطبوط ذكي لانة بيعيش لوحده طول عمره، ما عدا في وقت التزاوج، وبيقدر يتعلم من بعيد، من غير ما يخوض التجربة بنفسه، وبيقدر يربط حدث بنتيجة، وبيقدر يهرب من المفترس بتقنيات مختلفة، زي التمويه والتحول لاسماك مختلفة، وبيقدر يتعلم بالمشاهدة، وبيقدر يربط بين المعلومات الاستخباراتية.

المصدر: الأخطبوط الدحيح | رتبة: 1
السؤال خارج نطاق المحتوى المتاح.
Prompt chars: 0

A) Full History Visualization

In [32]:
memory_full = ConversationMemory()

rag_full = RAGPipeline(
    retriever=retriever,
    llm=llm,
    prompt_type="strict",
    memory=memory_full,
    use_memory=True,
    memory_strategy="full"
)

rag_full.answer("الأخطبوط ذكي ازاي؟")
rag_full.answer("طب هو بيستخدم الحبر ليه؟")

print("FULL MEMORY:")
print(memory_full.get_full_history_text())

print("\n" + "="*80 + "\n")

print("FULL STRATEGY HISTORY SENT TO MODEL:")
print(
    memory_full.get_history_text(strategy="full")
)

FULL MEMORY:
User: الأخطبوط ذكي ازاي؟
Assistant: الأخطبوط ذكي لانة بتعلم من بعيد، بيعيش لوحده طول عمره، وبيستخدم الية موجودة زي التمويه والتحول لالوان مختلفة، وبيستخدم بروتينات حساسة للضوء في عينيه وجلده.

المصدر: الأخطبوط الدحيح | رتبة: 1

================================================================================

FULL STRATEGY HISTORY SENT TO MODEL:
User: الأخطبوط ذكي ازاي؟
Assistant: الأخطبوط ذكي لانة بتعلم من بعيد، بيعيش لوحده طول عمره، وبيستخدم الية موجودة زي التمويه والتحول لالوان مختلفة، وبيستخدم بروتينات حساسة للضوء في عينيه وجلده.

المصدر: الأخطبوط الدحيح | رتبة: 1

B) Sliding Window Visualization

In [33]:
memory_sliding = ConversationMemory()

rag_sliding = RAGPipeline(
    retriever=retriever,
    llm=llm,
    prompt_type="strict",
    memory=memory_sliding,
    use_memory=True,
    memory_strategy="sliding",
    last_n_turns=1
)

rag_sliding.answer("الأخطبوط ذكي ازاي؟")
rag_sliding.answer("طب هو بيستخدم الحبر ليه؟")

print("FULL STORED MEMORY:")
print(memory_sliding.get_full_history_text())

print("\n" + "="*80 + "\n")

print("SLIDING WINDOW HISTORY SENT TO MODEL:")
print(
    memory_sliding.get_history_text(
        strategy="sliding",
        last_n_turns=1
    )
)

FULL STORED MEMORY:
User: الأخطبوط ذكي ازاي؟
Assistant: الأخطبوط ذكي لانة بتستخدم الية موجودة في جسمها بطريقة استثنائية، زي مثلا، استخدام بروتينات حساسة للضوء في جلدها، ووجود خلايا الالوان في جلدها، و能力ها في التمويه والتحول لواني، و能力ها في التعلم من خلال المشاهدة، ووجود دراع مخصص للتزاوج في الذكر، و能力ها في التمويه والتحول لواني لتشويش المفترس.

[Source: الأخطبوط  الدحيح | Rank: 1]

================================================================================

SLIDING WINDOW HISTORY SENT TO MODEL:
User: الأخطبوط ذكي ازاي؟
Assistant: الأخطبوط ذكي لانة بتستخدم الية موجودة في جسمها بطريقة استثنائية، زي مثلا، استخدام بروتينات حساسة للضوء في جلدها، ووجود خلايا الالوان في جلدها، و能力ها في التمويه والتحول لواني، و能力ها في التعلم من خلال المشاهدة، ووجود دراع مخصص للتزاوج في الذكر، و能力ها في التمويه والتحول لواني لتشويش المفترس.

[Source: الأخطبوط  الدحيح | Rank: 1]

C) Truncation Visualization

In [34]:
memory_truncated = ConversationMemory()

rag_truncated = RAGPipeline(
    retriever=retriever,
    llm=llm,
    prompt_type="strict",
    memory=memory_truncated,
    use_memory=True,
    memory_strategy="truncated",
    max_history_chars=200
)

rag_truncated.answer("الأخطبوط ذكي ازاي؟")
rag_truncated.answer("طب هو بيستخدم الحبر ليه؟")

print("FULL STORED MEMORY:")
print(memory_truncated.get_full_history_text())

print("\n" + "="*80 + "\n")

print("TRUNCATED HISTORY SENT TO MODEL:")
print(
    memory_truncated.get_history_text(
        strategy="truncated",
        max_chars=200
    )
)

FULL STORED MEMORY:
User: الأخطبوط ذكي ازاي؟
Assistant: الأخطبوط ذكي لانة بتستخدم الية موجودة في جسمها بطريقة استثنائية، وبتستخدمها في التمويه والتحايل. وبتعلم من خلال المشاهدة، وبتستخدم بروتينات حساسة للضوء في جلدها لتشخيص الوان مختلفة.

================================================================================

TRUNCATED HISTORY SENT TO MODEL:
ي ازاي؟
Assistant: الأخطبوط ذكي لانة بتستخدم الية موجودة في جسمها بطريقة استثنائية، وبتستخدمها في التمويه والتحايل. وبتعلم من خلال المشاهدة، وبتستخدم بروتينات حساسة للضوء في جلدها لتشخيص الوان مختلفة.

D) Summarized History

In [35]:
memory_summary = ConversationMemory()

rag_summary = RAGPipeline(
    retriever=retriever,
    llm=llm,
    prompt_type="strict",
    memory=memory_summary,
    use_memory=True,
    memory_strategy="summarized"
)

rag_summary.answer("الأخطبوط ذكي ازاي؟")
rag_summary.answer("طب هو بيستخدم الحبر ليه؟")

print("FULL MEMORY:")
print(memory_summary.get_full_history_text())

print("\n" + "="*80 + "\n")

print("SUMMARIZED HISTORY SENT TO MODEL:")
print(
    memory_summary.get_history_text(
        strategy="summarized",
        llm=llm
    )
)

FULL MEMORY:
User: الأخطبوط ذكي ازاي؟
Assistant: حدث خطأ أثناء توليد الإجابة. من فضلك حاول مرة أخرى لاحقا.

================================================================================

SUMMARIZED HISTORY SENT TO MODEL:
لا يوجد معلومات مفيدة في هذا الحوار لإنتهاءه بشكل غير متوقع.

Cache

In [36]:
from pathlib import Path
from semantic_cache import SemanticCache
from conversation_memory import ConversationMemory
from rag_pipeline_ import RAGPipeline
from llm_client_openai import OpenAILLM

CACHE_PATH = PROJECT_ROOT / "data" / "cache" / "semantic_cache.json"

semantic_cache = SemanticCache(
    embedding_model=embedding_model,
    cache_path=CACHE_PATH,
    similarity_threshold=0.85
)

semantic_cache.clear()

llm = GroqLLM()
memory = ConversationMemory()

rag_cached = RAGPipeline(
    retriever=retriever,
    llm=llm,
    memory=memory,
    memory_strategy="sliding",
    semantic_cache=semantic_cache,
    use_cache=True
)

print("Cache entries:", semantic_cache.count())

Cache entries: 0

In [37]:
result1 = rag_cached.answer("الأخطبوط ذكي ازاي؟")

print("Cache hit:", result1["cache_hit"])
print("Cache entries:", semantic_cache.count())
print(result1["answer"])

Cache hit: False
Cache entries: 1
حدث خطأ أثناء توليد الإجابة. من فضلك حاول مرة أخرى لاحقا.

In [38]:
result2 = rag_cached.answer("ليه الأخطبوط يعتبر ذكي؟")

print("Cache hit:", result2["cache_hit"])
print("Similarity:", result2["cache_similarity"])
print("Matched question:", result2["matched_question"])
print(result2["answer"])

Cache hit: True
Similarity: 0.9240501019937778
Matched question: الأخطبوط ذكي ازاي؟
حدث خطأ أثناء توليد الإجابة. من فضلك حاول مرة أخرى لاحقا.

In [39]:
# test_questions = [
#     "الأخطبوط ذكي ازاي؟",
#     "ليه الأخطبوط يعتبر ذكي؟",
#     "ما سبب ذكاء الأخطبوط؟",
#     "الأخطبوط بيستخدم الحبر ليه؟",
#     "ما وظيفة الحبر عند الأخطبوط؟",
#     "تاج محل اتبنى ليه؟",
#     "مين بنى تاج محل؟"
# ]

# thresholds = [0.75, 0.80, 0.85, 0.88, 0.90, 0.95]

# results = []

# for threshold in thresholds:
#     semantic_cache.clear()
#     semantic_cache.similarity_threshold = threshold

#     cache_hits = 0
#     llm_calls = 0

#     for question in test_questions:
#         result = rag_cached.answer(question)

#         if result["cache_hit"]:
#             cache_hits += 1
#         else:
#             llm_calls += 1

#     hit_rate = cache_hits / len(test_questions)
#     saved_model_calls = cache_hits

#     results.append({
#         "threshold": threshold,
#         "cache_hits": cache_hits,
#         "llm_calls": llm_calls,
#         "hit_rate": hit_rate,
#         "saved_model_calls": saved_model_calls
#     })

# results

Out of Domain Detection

In [40]:
from rag_pipeline_ import RAGPipeline
from conversation_memory import ConversationMemory
from llm_client_openai import OpenAILLM
from llm_client_groq import GroqLLM

primary_llm = GroqLLM(model_name="llama-3.1-8b-instant")
fallback_llm =  HuggingFaceLLM(
    model_name="Qwen/Qwen2.5-7B-Instruct"
)


memory = ConversationMemory()

rag_safe = RAGPipeline(
    retriever=retriever,
    llm=primary_llm,
    fallback_llm=fallback_llm,
    memory=memory,
    memory_strategy="sliding",
    semantic_cache=semantic_cache,
    use_cache=True,
    out_of_domain_threshold=0.45,
    max_retries=2
)

In [41]:
result = rag_safe.answer("الأخطبوط ذكي ازاي؟")

print(result["answer"])
print("Out of domain:", result["out_of_domain"])
print("Retrieval score:", result.get("retrieval_score"))

حدث خطأ أثناء توليد الإجابة. من فضلك حاول مرة أخرى لاحقا.
Out of domain: False
Retrieval score: None

Retrieval score: None means that result probably came from cache, because cached responses skip retrieval and return retrieved_chunks=[]

In [42]:
print("Cache hit:", result.get("cache_hit"))

Cache hit: True

In [43]:
result = rag_safe.answer("Who won the World Cup 2022?")

print(result["answer"])
print("Out of domain:", result["out_of_domain"])
print("Retrieval score:", result.get("retrieval_score"))

السؤال خارج نطاق المحتوى المتاح.
Out of domain: True
Retrieval score: 0.39771668002328286

Evaluation Metrics

In [44]:
from pathlib import Path
import pandas as pd

from evaluation import load_test_sets, run_rag_evaluation

TEST_DIR = PROJECT_ROOT / "data" / "QA test"

test_items = load_test_sets(TEST_DIR)

print("Total loaded:", len(test_items))
print(test_items[0])

Total loaded: 44
{'question': 'ما الظاهرة التي يحاول البحث تفسيرها في بداية الحلقة؟', 'reference_answer': 'الانفجار الكامبري', 'context': 'البحث بيحاول يجاوب على سؤال... ما هو سبب الانفجار الكامبري؟', 'title': 'octopus_test_set', 'source_file': 'octopus_test_set.json', 'id': 'Q1'}

In [45]:
import os
import warnings
import logging

os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

warnings.filterwarnings("ignore")

logging.getLogger("transformers").setLevel(logging.ERROR)
logging.getLogger("huggingface_hub").setLevel(logging.ERROR)

In [46]:
from llm_client_groq import GroqLLM
from llm_client_openai import OpenAILLM
from llm_client_hf import HuggingFaceLLM

models = {
    "Groq": GroqLLM(
        model_name="llama-3.1-8b-instant"
    ),

    # "OpenAI": OpenAILLM(
    #     model_name="gpt-3.5-turbo"
    # ),

    "HuggingFace_Qwen": HuggingFaceLLM(
        model_name="Qwen/Qwen2.5-7B-Instruct"
    )
}

In [47]:
from rag_pipeline_ import RAGPipeline
from conversation_memory import ConversationMemory

all_results = []

for evaluated_model_name, llm in models.items():
    print("=" * 80)
    print("Evaluating:", evaluated_model_name)

    eval_memory = ConversationMemory()

    rag_eval = RAGPipeline(
        retriever=retriever,
        llm=llm,
        memory=eval_memory,
        use_memory=False,
        memory_strategy="sliding",
        semantic_cache=semantic_cache,
        use_cache=False,
        out_of_domain_threshold=0.45,
        max_retries=2
    )

    model_results = run_rag_evaluation(
        rag_pipeline=rag_eval,
        test_items=test_items,
        embedding_model=embedding_model
    )

    for row in model_results:
        row["evaluated_model"] = evaluated_model_name

    all_results.extend(model_results)

print("Evaluation finished.")

================================================================================
Evaluating: Groq

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

================================================================================
Evaluating: HuggingFace_Qwen

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Evaluation finished.

In [48]:
df_eval = pd.DataFrame(all_results)

df_eval.head()

,question_id,source_file,question,reference_answer,generated_answer,semantic_similarity,grounding_score,bert_score,latency_seconds,cache_hit,out_of_domain,model,memory_strategy,evaluated_model
0,1,octopus_test_set.json,ما الظاهرة التي يحاول البحث تفسيرها في بداية ا...,الانفجار الكامبري,حدث خطأ أثناء توليد الإجابة. من فضلك حاول مرة ...,0.283313,0.272727,0.660203,43.918025,False,False,primary_failed,sliding,Groq
1,2,octopus_test_set.json,منذ متى حدث الانفجار الكامبري تقريبًا؟,منذ حوالي 541 مليون سنة,لا توجد معلومات كافية في النص للإجابة عن هذا ا...,0.225996,0.400000,0.517814,0.691052,False,False,llama-3.1-8b-instant,sliding,Groq
2,3,octopus_test_set.json,ما الفرضية التي تقترح أن سبب الانفجار الكامبري...,أن السبب قد يكون كونيًا مثل فيروسات أو مواد جا...,لا توجد معلومات كافية في النص للإجابة عن هذا ا...,0.324141,0.210526,0.646651,37.679507,False,False,llama-3.1-8b-instant,sliding,Groq
3,4,octopus_test_set.json,لماذا لم يقبل العلماء فرضية الأصل الفضائي للأخ...,لعدم وجود دليل مباشر,لا توجد معلومات كافية في النص للإجابة عن هذا ا...,0.507218,0.266667,0.624739,42.285728,False,False,llama-3.1-8b-instant,sliding,Groq
4,5,octopus_test_set.json,إلى أي شعبة ينتمي الأخطبوط؟,الرخويات,ينتمي الأخطبوط إلى شعبة راسيات الأرجل.\n\nالأخ...,0.394542,0.111111,0.623112,43.937205,False,False,llama-3.1-8b-instant,sliding,Groq

In [49]:
model_summary = df_eval.groupby("evaluated_model").agg({
    "bert_score": "mean",
    "semantic_similarity": "mean",
    "grounding_score": "mean",
    "latency_seconds": "mean"
}).reset_index()

model_summary

,evaluated_model,bert_score,semantic_similarity,grounding_score,latency_seconds
0,Groq,0.660916,0.186955,0.162957,5.166190
1,HuggingFace_Qwen,0.652252,0.340104,0.359987,1.753567

In [50]:
file_summary = df_eval.groupby(
    ["evaluated_model", "source_file"]
).agg({
   "bert_score": "mean",
    "semantic_similarity": "mean",
    "grounding_score": "mean",
    "latency_seconds": "mean"
}).reset_index()

file_summary

,evaluated_model,source_file,bert_score,semantic_similarity,grounding_score,latency_seconds
0,Groq,octopus_test_set.json,0.634900,0.273182,0.235194,21.325715
1,Groq,physics_movement_test_set.json,0.666573,0.190163,0.166667,0.472009
2,Groq,samurai_test_set.json,0.677153,0.115544,0.166667,0.414741
3,Groq,taj_mahal_test_set.json,0.660657,0.182572,0.081818,0.341420
4,HuggingFace_Qwen,octopus_test_set.json,0.658759,0.337629,0.296513,1.298012
5,HuggingFace_Qwen,physics_movement_test_set.json,0.614081,0.251719,0.390182,1.851077
6,HuggingFace_Qwen,samurai_test_set.json,0.685616,0.500368,0.468447,2.704863
7,HuggingFace_Qwen,taj_mahal_test_set.json,0.651513,0.256323,0.257072,0.950554

In [51]:
metrics_summary = {
    
    "Best Semantic Similarity": {
        "model": model_summary.loc[model_summary["semantic_similarity"].idxmax(), "evaluated_model"],
        "value": model_summary["semantic_similarity"].max()
    },
    "Best Grounding Score": {
        "model": model_summary.loc[model_summary["grounding_score"].idxmax(), "evaluated_model"],
        "value": model_summary["grounding_score"].max()
    },
    "Fastest Model": {
        "model": model_summary.loc[model_summary["latency_seconds"].idxmin(), "evaluated_model"],
        "value": model_summary["latency_seconds"].min()
    }
}

metrics_summary

{'Best Semantic Similarity': {'model': 'HuggingFace_Qwen',
  'value': np.float64(0.3401037781837989)},
 'Best Grounding Score': {'model': 'HuggingFace_Qwen',
  'value': np.float64(0.3599865042789187)},
 'Fastest Model': {'model': 'HuggingFace_Qwen',
  'value': np.float64(1.7535670833154158)}}

In [52]:
EVAL_OUTPUT_DIR = PROJECT_ROOT / "data" / "evaluation_results"
EVAL_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

df_eval.to_csv(
    EVAL_OUTPUT_DIR / "all_model_rag_evaluation_results_2.csv",
    index=False,
    encoding="utf-8-sig"
)

model_summary.to_csv(
    EVAL_OUTPUT_DIR / "model_comparison_summary_2.csv",
    index=False,
    encoding="utf-8-sig"
)

file_summary.to_csv(
    EVAL_OUTPUT_DIR / "model_comparison_by_file_2.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Saved evaluation results to:", EVAL_OUTPUT_DIR)

Saved evaluation results to: c:\Users\Nadine Samir\Marina\NLP-project\data\evaluation_results

In [53]:
print("All Models:")
display(model_summary)

print("Best BERTScore:")
display(
    model_summary.loc[
        [model_summary["bert_score"].idxmax()]
    ]
)

All Models:

,evaluated_model,bert_score,semantic_similarity,grounding_score,latency_seconds
0,Groq,0.660916,0.186955,0.162957,5.166190
1,HuggingFace_Qwen,0.652252,0.340104,0.359987,1.753567

Best BERTScore:

,evaluated_model,bert_score,semantic_similarity,grounding_score,latency_seconds
0,Groq,0.660916,0.186955,0.162957,5.16619